config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Scrippet::Application.routes.draw do 
  mount StripeEvent::Engine => '/stripe'
  resources :notes_accessors, path: 'permissions'
  resources :notes, path: 'stickys'
  resources :projects
  get 'mystickys' => 'notes#index'
  get 'shared' => 'notes#index'
  get 'dashboard' => 'home#dashboard'
  get 'messages' => 'home#plans'
  resources :categories
  resources :posts, path: 'scrippets'
  get 'tags/:tag', to: 'posts#index', as: :tag  
  devise_for :users, controllers: { :registrations => 'registrations' }, path: 'scrippers'
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end 
  resources :users, path: 'scrippers' do
    member do
      get :follow, :unfollow, :block, :unblock    
    end
  end
  get 'followers' => 'users#index'
  get 'following' => 'users#index'

  constraints(SubdomainPresent) do
    get 'welcome' => 'home#welcome'
    root 'home#index', as: :subdomain_root
  end

  constraints(SubdomainBlank) do   
    get 'join' => 'home#join' 
    resources :tenants, only: [:new, :create] 
    root 'home#index'   
  end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def join
  end

  def welcome
  end

  def dashboard
  end

  def index
    @posts = Post.order('publish_date DESC').limit(1)
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<% if request.path == root_path %>

<% end %>

app/views/home/index.html.erb
<% if current_user %>
<div class="welcomepg"><%= current_user.name %></div>
<% else %>

<div class="centerdiv">
  <div class="app_available nbpapernoglow">
    <%= image_tag('phones.png', border: 0, class: 'phones_img') %>
   
   <div class="header_txt">
    <strong>Scrippet for writers</strong><br /><br />
    <p data-toggle="modal" href="#whatisscrippet" type="button">What is Scrippet? Click here to find out</p>
<%= link_to 'Lease Private Subdomain', join_path, class: 'btn btn-warning home-btn' %>
    <%= link_to 'Join Scrippet Community', new_user_registration_path, class: 'btn btn-warning home-btn' %>

   </div>
    
   <div class="home_buttons"> 
     <%= link_to image_tag('play_g.png', border: 0, class: 'app-btn'), 'javascript:;' %>
     <%= link_to image_tag('app_g.png', border: 0, class: 'app-btn'), 'javascript:;' %>
   </div>

  </div>
  <div class="signin nbpapernoglow">
    <%= simple_form_for(:user, :url => session_path(:user), html: {id:'signin_form'}) do |f| %>
      <div class="signin_header"><strong>Sign in</strong> to Scrippet</div>
        <div class="input-group">
          <span class="input-group-addon">
              <span class="glyphicon glyphicon-user"></span>
          </span>
          <%= f.text_field :email, placeholder: 'Enter your Email', class: 'form-control', autofocus: true %>           
        </div>
       <br />
        <div class="input-group">
          <span class="input-group-addon">
              <span class="glyphicon glyphicon-lock"></span>
          </span>
          <%= f.text_field :password, placeholder: 'Enter your Password', class: 'form-control' %> 
        </div>

      <div class="signin_controls">
        <div class="btn-group">
          <%= link_to "Forgot?", new_password_path(:user), class: 'btn btn-height btn-default' %>
          <%= f.submit 'Sign in', class: 'btn btn-height btn-warning' %>
        </div>
      </div>
    <% end %>
  </div>


</div>


<div id="whatisscrippet" class="modal" style="display: none;">
  Yadda yadda yadda
</div>

<% end %>

app/views/home/join.html.erb
<div class="joinpage">
<h2 style="color:#fff;">There are two ways to Join Scrippet:</h2>
<br /><br />

  <div class="joinblock nbpaper" style="float:left;">
    <div class="joinhead"><h1>Sign up for Scrippet</h1></div>
    <div class="unstyled joinlist">
      Find inspiration to help jumpstart your project<br />
      Share your ideas with other writers<br />
      Collaborate with others on projects<br />
      Collaborate with others on projects<br />
    </div>
    <%= link_to 'Sign Up Free!', new_user_registration_path, :class => 'btn btn-warning btn-lg' %>
  </div>

<div class="plans">
  <div class="welll featured nbpapernoglow">
    <div class="planhead"><h1>Scripper</h1></div>
    <div class="features">
      Automatic Database Backups<br />
      Exclusive to your group<br />
      10 registered users<br />
      100 notecards per user
    </div>
    <div class="pricee">$7 /month</div><br /><br />
    <div class="tenantFields">
    <%= link_to 'Sign Up Now!', new_tenant_path(:plan => 'scripper'), :class => 'btn btn-warning' %>
    </div>
  </div>

  <div class="welll featured nbpapernoglow">
    <div class="planhead featured-plan"><h1>Scrippeter</h1></div>
    <div class="features">
      Automatic Database Backups<br />
      Exclusive to your group<br />
      25 registered users<br />
      250 notecards per user
    </div>
    <div class="pricee">$17 /month</div><br /><br />
    <div class="tenantFields">
    <%= link_to 'Sign Up Now!', new_tenant_path(:plan => 'scrippeter'), :class => 'btn btn-warning' %> 
    </div>
  </div>

  <div class="welll featured nbpapernoglow">
    <div class="planhead"><h1>Scripperator</h1></div>
    <div class="features">
      Automatic Database Backups<br />
      Exclusive to your group<br />
      50 registered users<br />
      500 notecards per user
    </div>
    <div class="pricee">$27 /month</div><br /><br />
    <div class="tenantFields">
    <%= link_to 'Sign Up Now!', new_tenant_path(:plan => 'scripperator'), :class => 'btn btn-warning' %> 
    </div>
</div>

</div>

app/views/home/plans.html.erb
<% @signup_pg = true %>

<div class="plans">
<h2 style="color:#fff;">New Tenant Signup Options</h2><br /><br />
  <div class="welll featured nbpapernoglow">
    <div class="plan"><h1>Scripper</h1></div>
    <div class="features">
      Automatic Database Backups<br />
      Exclusive to your group<br />
      10 registered users<br />
      100 notecards per user
    </div>
    <h2 style="color:#f0a441;">$7 /month</h2><br /><br />
    <div class="tenantFields">
    <%= link_to 'Subscribe', new_user_registration_path(:plan => 'scripper'), :class => 'btn btn-warning' %>
    </div>
  </div>

  <div class="welll featured nbpapernoglow">
    <div class="plan featured-plan"><h1>Scrippeter</h1></div>
    <div class="features">
      Automatic Database Backups<br />
      Exclusive to your group<br />
      25 registered users<br />
      250 notecards per user
    </div>
    <h2 style="color:#f0a441;">$17 /month</h2><br /><br />
    <div class="tenantFields">
    <%= link_to 'Subscribe', new_user_registration_path(:plan => 'scrippeter'), :class => 'btn btn-warning' %> 
    </div>
  </div>

  <div class="welll featured nbpapernoglow">
    <div class="plan"><h1>Scripperator</h1></div>
    <div class="features">
      Automatic Database Backups<br />
      Exclusive to your group<br />
      50 registered users<br />
      500 notecards per user
    </div>
    <h2 style="color:#f0a441;">$27 /month</h2><br /><br />
    <div class="tenantFields">
    <%= link_to 'Subscribe', new_user_registration_path(:plan => 'scrippeter'), :class => 'btn btn-warning' %> 
    </div>
</div>

app/views/home/welcome.html.erb
<script language="JavaScript" type="text/javascript">  
var count =0  
var redirect="<%= posts_path %>"
  
function countDown(){  
 if (count <=0){  
  window.location = redirect;  
 }else{  
  count--;  
  document.getElementById("timer").innerHTML = "This page will redirect in "+count+" seconds."  
  setTimeout("countDown()", 1000)  
 }  
}  
</script>  

<div class="welcomepg">
  Welcome!
</div>

<span id="timer" style="display:none;">  
<script>  
 countDown();  
</script>  
</span>  