config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Scrippet::Application.routes.draw do 
  mount StripeEvent::Engine => '/stripe'
  resources :notes_accessors, path: 'permissions'
  resources :notes, path: 'stickys'
  resources :projects
  get 'mystickys' => 'notes#index'
  get 'shared' => 'notes#index'
  get 'dashboard' => 'home#dashboard'
  get 'messages' => 'home#plans'
  resources :categories
  resources :posts, path: 'scrippets'
  get 'tags/:tag', to: 'posts#index', as: :tag  
  devise_for :users, controllers: { :registrations => 'registrations' }, path: 'scrippers'
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end 
  resources :users, path: 'scrippers' do
    member do
      get :follow, :unfollow, :block, :unblock    
    end
  end
  get 'followers' => 'users#index'
  get 'following' => 'users#index'

  constraints(SubdomainPresent) do
    get 'welcome' => 'home#welcome'
    root 'home#index', as: :subdomain_root
  end

  constraints(SubdomainBlank) do   
    get 'join' => 'home#join' 
    resources :tenants, only: [:new, :create] 
    root 'home#index'   
  end 
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_taggable
  validates_presence_of :title, :body, :publish_date, :user_id 
 # validates :terms, acceptance: true
  belongs_to :user
  has_and_belongs_to_many :categories
  scope :published, lambda { where(['publish_date <= ?', Date.today]) }
  scope :by_user_id, lambda {|uid| where(:user_id => uid)}
  scope :by_category_id, lambda {|cid| joins(:categories).where(['categories.id =?',cid])}
 
  include PgSearch
  pg_search_scope :search, against: [:title, :body],
  using: {tsearch: {dictionary: "english"}},
 # associated_against: {author: :name, comments: [:name, :content]},
  ignoring: :accents

  def self.text_search(query)
  if query.present?
    rank = <<-RANK
      ts_rank(to_tsvector(title), plainto_tsquery(#{sanitize(query)})) +
      ts_rank(to_tsvector(body), plainto_tsquery(#{sanitize(query)}))
    RANK
    where("to_tsvector('english', title) @@ :q or to_tsvector('english', body) @@ :q", q: query).order("#{rank} desc")
  else
    scoped
  end
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => :index
 # load_and_authorize_resource 

  # GET /posts
  def index
    @posts = Post.order('publish_date DESC')
    @posts = @posts.published if current_user.blank?
    @posts = @posts.by_user_id(params[:user]) if params[:user].present?
    @posts = @posts.by_category_id(params[:cat]) if params[:cat].present?
    @posts = @posts.tagged_with(params[:tag]) if params[:tag].present?
    @posts = @posts.text_search(params[:query]).page(params[:page])#.per_page(3)
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post, notice: 'Scrippet Saved.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Scrippet Saved.'
    else
      render action: 'edit'
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:title, :body, :publish_date, :user_id, :adult, :terms, :tag_list, category_ids: [])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for @post, validate: true do |f| %> 
   <div class="new_scrippet_heading">
     <h3><strong>Category:</strong></h3>   
    <div class="btn-group cat-group" data-toggle="buttons">
      <label class="btn btn-warning cat-btn">  
        <%= f.association :categories, collection: Category.where(id: 1), as: :check_boxes, label: false %>  
      </label>
      <label class="btn btn-warning cat-btn">
        <%= f.association :categories, collection: Category.where(id: 2), as: :check_boxes, label: false %>
      </label>
      <label class="btn btn-warning cat-btn">  
        <%= f.association :categories, collection: Category.where(id: 3), as: :check_boxes, label: false %>  
      </label>
      <label class="btn btn-warning cat-btn">
        <%= f.association :categories, collection: Category.where(id: 4), as: :check_boxes, label: false %>
      </label>
      <label class="btn btn-warning cat-btn">
        <%= f.association :categories, collection: Category.where(id: 5), as: :check_boxes, label: false %>
      </label>
    </div>
  </div>
<div class="nbpapernoglow scripform">  
   <div class="titlebg">
    <%= f.input :title, input_html: { placeholder: 'Scrippet Title'}, label: false %>
   </div>
   
   <%= f.input :body, input_html: { placeholder: 'Type or Paste your Scrippet!'}, label: false %>
</div>
   
  <div class="scrippet_tags">
    <h4>Type in your tags in the box below. Seperate by commas</h4>
    <%= f.input :tag_list, input_html: { id: :post_tags }, label: false  %>
  </div>

  <div class="form-actions">
    <div class="post_buttons">
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  posts_path, class: 'btn btn-default' %>
      <%= f.button :submit, 'Submit Scrippet', class: 'btn btn-warning' %>
    </div> 

    <div class="btn-group" data-toggle="buttons">
      <label class="btn btn-default">  
        <%= f.input :adult, inline_label: 'Adult Material? (18+)', label: false %>
      </label>
      <label class="btn btn-default"> 
        <%= f.input :terms, label: false, 
            inline_label: 'Agree to Terms? (required)' %>
      </label>
    </div>

    <div class="btn-plain pubdate">Publish Date: <%= f.text_field :publish_date %></div>
 
  </div>

<% end %>

app/views/posts/_scrippets.html.erb
<% @posts.each do |post| %>

  <%= link_to post_path(post), :class => 'fill-div' do %>
<div class="scrip">
  <div id="scrippet" class="">
  <div class="scriphead">
  <h7><%= post.title %></h7>
  </div>
      <%= post.body %>
    </div>    
    <% end %>    
    <div class="scriptions">
     <div class="scrinfo">
      <strong><%= link_to post.user.name.truncate(17), post.user, :class => 'scrinfo', "data-toggle" => "tooltip", "data-placement" => "top", "title" => "View Scrippets by #{post.user.name}" %></strong><br />
      <%= l post.publish_date, format: :long %><br />      
     </div>
      <div class="btn-group dropup pad" style="float:right;">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
       <span class="glyphicon glyphicon-align-justify white"></span></a>
        <ul class="dropdown-menu optionmenu pull-right">
        <% if current_user && (current_user.has_role?(:admin) || current_user.id == post.user_id) %>
          <li><%= link_to edit_post_path(post), :class => 'optiondivider' do %>
            <span class="glyphicon glyphicon-pencil"></span> Edit<% end %></li>      
          <li><%= link_to post, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-trash"></span> Delete<% end %></li>
          <li class="divider"></li>
        <% end %>
        <% if current_user && current_user.id != post.user_id %>
          <li>
           <% if current_user.following?(post.user) %>
              <%= link_to unfollow_user_path(post.user) do %>
                <span class="glyphicon glyphicon-thumbs-up"></span> Unfollow
              <% end %>
           <% else %>
              <%= link_to follow_user_path(post.user) do %>
                <span class="glyphicon glyphicon-thumbs-up"></span> Follow
              <% end %>
           <% end %>
          </li>
          <li class="divider"></li>
        <% end %>       
        <li><%= link_to dashboard_path do %><span class="glyphicon glyphicon-thumbs-up"></span> Share<% end %></li>       
       </ul>  
    
     </div>
     <div class="btn-group dropup pad" style="float:right;">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
       <span class="glyphicon glyphicon-tags white"></span></a>
       <ul class="dropdown-menu tagmenu pull-right">
       <!-- <li><span class="glyphicon glyphicon-tag" style="margin-left:10px;"></span>Search a tag</li> 
        <li class="divider"></li> -->
         <li><div class="notag"><%= "No Scrippet Tags" if post.tags.none? %></div><%= raw post.tag_list.map { |t| link_to t, tag_path(t) }.join() %></li>
       </ul>      
     </div>
    </div>
</div>
<% end %>

<% unless request.path == posts_path || request.path == root_path || @user.posts.count < 4 %>

<div class="see_user_posts">
  <%= link_to posts_path(:user => @user.id) do %>
      See all <%= @user.posts.count %> of <%= @user.name %>'s Scrippets 
  <% end %>
</div>
<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<h3 class="pgheader">Edit Scrippet Post</h3>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<div class="tagdiv">

  <%= form_tag posts_path, method: :get do %>
    <div class="input-group">
      <%= text_field_tag :query, params[:query], class: 'form-control' %>
      <span class="input-group-addon">
        <%= button_tag(type: "submit", class: "search_btn") do %>
          <span class="glyphicon glyphicon-search"></span>
        <% end %>
      </span>
    </div>
  <% end %>
  <br />
  <div id="tag_cloud">
    <% tag_cloud Post.tag_counts, %w[s m l] do |tag, css_class| %>
      <%= link_to tag.name, tag_path(tag.name), class: css_class %>
    <% end %>
  </div>
</div>

<div class="scripage">
  <%= render partial: 'scrippets' %>
</div>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<%= render partial: 'form' %>

app/views/posts/post_tag_list.html.erb
[{id: 72, name: "Mystery"},
{id: 11, name: "Comedy"},
{id: 13, name: "Adventure"},
{id: 17, name: "ActionScript"},
{id: 19, name: "Scheme"},
{id: 23, name: "Lisp"},
{id: 29, name: "C#"},
{id: 31, name: "Fortran"},
{id: 37, name: "Visual Basic"},
{id: 41, name: "C"},
{id: 43, name: "C++"}, 
{id: 47, name: "Java"}]

app/views/posts/show.html.erb
<% @scripbg_pg = true %>

<%- model_class = Post -%>
<div class="scripShow">
  <div class="titlebg titleShow"><%= @post.title %></div>
  <div class="bodyShow"><%= @post.body %></div>
  <div class="tagsShow">Scrippet Tags: <%= raw @post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></div><br />

<div class="form-actions show" style="margin:0px;"> 
  <div class="post_buttons"> 
    <%= link_to t('.back', :default => t("i'm done reading")),
                posts_path, :class => 'btn btn-warning'  %>
    <% if current_user && (current_user.has_role?(:admin) || current_user.id == @post.user_id) %>
      <%= link_to t('.edit', :default => t("edit/change")),
                edit_post_path(@post), :class => 'btn btn-default' %>
      <%= link_to t('.destroy', :default => t("delete scrippet")),
                post_path(@post),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-default' %>
    <% end %>
  </div>
  <%= link_to @post.user, "data-toggle" => "tooltip", "data-placement" => "top", "title" => "View Scrippets by #{@post.user.name}" do %>
  <span class="btn btn-plain publishedby">This Scrippet was Published on 
    <strong><%= @post.publish_date %></strong> by <strong>
    <% if @post.user == current_user %>
      <%= @post.user.name.truncate(30) %>
    <% else %>
      <%= @post.user.name.truncate(20) %>
    <% end %></strong></span>
  <% end %>
</div>
</div>