config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Scrippet::Application.routes.draw do 
  mount StripeEvent::Engine => '/stripe'
  resources :notes_accessors, path: 'permissions'
  resources :notes, path: 'stickys'
  resources :projects
  get 'mystickys' => 'notes#index'
  get 'shared' => 'notes#index'
  get 'dashboard' => 'home#dashboard'
  get 'messages' => 'home#plans'
  resources :categories
  resources :posts, path: 'scrippets'
  get 'tags/:tag', to: 'posts#index', as: :tag  
  devise_for :users, controllers: { :registrations => 'registrations' }, path: 'scrippers'
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end 
  resources :users, path: 'scrippers' do
    member do
      get :follow, :unfollow, :block, :unblock    
    end
  end
  get 'followers' => 'users#index'
  get 'following' => 'users#index'

  constraints(SubdomainPresent) do
    get 'welcome' => 'home#welcome'
    root 'home#index', as: :subdomain_root
  end

  constraints(SubdomainBlank) do   
    get 'join' => 'home#join' 
    resources :tenants, only: [:new, :create] 
    root 'home#index'   
  end 
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_main.html.erb
<div id="nav_main">
<div class="logo">
  <%= link_to image_tag("logo.png", border: 0, class: 'brand'), posts_path if current_user %>
  <%= link_to image_tag("logo.png", border: 0, class: 'brand'), root_path unless current_user %>
</div>

<%= render partial: 'layouts/login_buttons' %>

<% if user_signed_in? %>
  <ul class="nav">
    <li>
      <%= link_to 'Scrippet Post'.upcase, posts_path %>
    </li>  
    <li>
      <%= link_to 'Sticky Board'.upcase, notes_path %>
    </li> 
    <li>
      <%= link_to 'Projects'.upcase, projects_path %>
    </li> 
    <li>
      <%= link_to followers_path do %>FOLLOWERS: <span class="orange">
      <%= current_user.count_user_followers %></span><% end %>
    </li>        
    <li>     
      <%= link_to following_path do %>FOLLOWING: <span class="orange">
      <%= current_user.following_users_count %></span><% end %>
    </li>
    <% if current_user.has_role? :admin %>         
     
    <% end %>   
  </ul>         
<% else %>
  <ul class="nav">
    <li>      
      <span class="head-caption">Enabling writers and inspiring creativity</span>
    </li>
  </ul>
<% end %>
</div>

app/views/layouts/_nav_notes.html.erb
<div class="nav3menu btn-group">
    <%= link_to 'Add Sticky', new_note_path, class: 'btn btn-default' %> 
    <a class="btn btn-default dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-align-justify gray"></span></a>
      <ul class="dropdown-menu pull-right gray">
        <li><%= link_to new_note_path do %><span class="glyphicon glyphicon-plus"></span> Add Sticky<% end %></li>
        <li><%= link_to notes_accessors_path do %><span class="glyphicon glyphicon-lock"></span> Permissions<% end %></li>
        <li class="divider"></li>
        <li><%= link_to notes_path do %><span class="glyphicon glyphicon-user"></span> All Stickys<% end %></li>         
        <li class="divider"></li>
        <li><%= link_to mystickys_path do %><span class="glyphicon glyphicon-user"></span> My Stickys<% end %></li> 
        <li><%= link_to shared_path do %><span class="glyphicon glyphicon-check"></span> Shared Stickys<% end %></li>    
      </ul>
</div>

<div class="nav3div headerTxt">
  <strong><%= current_user.name %>'s Sticky Board</strong>&nbsp;&nbsp; -&nbsp;&nbsp;  
     <% if request.path == mystickys_path %>
        Showing Only My Notes
     <% elsif request.path == shared_path %>
        Notes Shared With Me
     <% else %>
        Showing All Sticky Notes
     <% end %>
</div>

app/views/layouts/_nav_posts.html.erb
<div class="nav2menu btn-group">
    <a class="btn btn-default dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-align-justify gray"></span></a>
      <ul class="dropdown-menu pull-right  gray">
        <li><%= link_to new_post_path do %><i class="glyphicon glyphicon-plus"></i> Post Scrippet<% end %></li>
        <li class="divider"></li>
        <li><%= link_to posts_path do %><i class="glyphicon glyphicon-user"></i> See All Scrippets<% end %></li>         
        <li class="divider"></li>
        <li><%= link_to posts_path(:user => current_user) do %><i class="glyphicon glyphicon-user"></i> My Scrippets<% end %></li> 
        <li><%= link_to shared_path do %><i class="glyphicon glyphicon-check"></i> Scrippet Users<% end %></li>    
      </ul>
</div>

<div class="nav2div">
   <% Category.all.each do |cat| %>      
      <%= link_to cat.name.upcase, posts_path(:cat => cat.id), :class => 'nav2text' %>
   <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Scrippet" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Scrippet" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-top">
        <div class="container">
          <%= render 'layouts/nav_main' %>
        </div>
      </nav>
      <% if request.path == posts_path %>
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/nav_posts' %>
        </div>
      </nav>
      <% end %>
      <% if @sticky_pg == true %>
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/nav_notes' %>
        </div>
      </nav>
      <% end %>
    </div>    
    <div>
      <%= render 'home/header' %>
    </div> 
    <div id="main" role="main">
      <% if request.path == notes_path %>
        <div class="content">
           <div class="row">
            <div>
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
           </div>
          <footer>
          </footer>
        </div>
      <% else %>
      <div class="container">
        <div class="content">
           <div class="row">
            <div>
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
           </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container --> 
      <% end %>
    </div> <!--! end of #main -->
  </body>
</html>